#!/usr/bin/env ruby
#^syntax detection

forge "https://forgeapi.puppetlabs.com"

# A module from the Puppet Forge
mod 'puppetlabs-apache'
mod 'puppetlabs-mysql'
mod 'puppetlabs-accounts'
mod 'puppet-php'
mod 'ftaeger-mailhog'

# A module from git
#mod 'puppetlabs-mysql',
#  :git => 'git://github.com/puppetlabs/puppetlabs-mysql'

# A module from a git branch/tag
# mod 'puppetlabs-apt',
#   :git => 'https://github.com/puppetlabs/puppetlabs-apt.git',
#   :ref => '1.4.x'

# A module from Github pre-packaged tarball
# mod 'puppetlabs-apache', '0.6.0', :github_tarball => 'puppetlabs/puppetlabs-apache'
